### ISSUE TITLE
Please describe IAM Policy requirements in the readme

### ISSUE THREAD

**Issue by trickidicki** [aws-samples/cookiecutter-aws-sam-pipeline#7]
Please describe IAM Policy requirements in the readme.

I enabled the following managed policies:
* AWSCodeCommitFullAccess 
* AWSLambdaFullAccess 
* IAMFullAccess 
* CloudFrontFullAccess 
* AWSCodePipelineFullAccess 
* AWSCodeBuildAdminAccess

plus the following manually-created policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1449904348000",
      "Effect": "Allow",
      "Action": [
        "cloudformation:CreateStack",
        "cloudformation:CreateChangeSet",
        "cloudformation:ListStacks",
        "cloudformation:UpdateStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackResource",
        "cloudformation:DescribeStackEvents",
        "cloudformation:ValidateTemplate",
        "cloudformation:DescribeChangeSet",
        "cloudformation:ExecuteChangeSet",
        "cloudformation:GetTemplateSummary"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**Comment by heitorlessa** [comment]
Hi @trickidicki - Thank you for opening this up and sharing what you've done so far. 

We do have the following in the `Pipeline instructions.md` that is generated at project creation:

> AWS CLI already configured with Administrator access

I'd love to hear your opinion on this: As `IAMFullAccess` in some way grants Admin access for one to create IAM Roles, Policies, etc. **Do you think there is still value in being more explicit with all service permissions?**

**Comment by heitorlessa** [comment]
Closing due to lack of updates, please reopen as soon as you have any.
